
# USA {#usa}

__Report last updated:__ `r Sys.Date()`

__Data last refreshed:__ : `r data_last_refreshed`


```{r, echo=FALSE, message=FALSE, cache=FALSE}
source("covid19_usa.R")
```


## Overall trend {#us-overall}

```{r, fig.width=8, fig.height=6, echo = FALSE, warning=FALSE}

p <- usa %>%
  group_by(date) %>%
  summarise(
    cum_cases = sum(cum_cases)
    , cum_deaths = sum(cum_deaths)
  ) %>% 
  gather(metric, n, cum_cases, cum_deaths, factor_key = TRUE) %>%
  mutate(
    metric = factor(metric, levels= c("cum_deaths", "cum_cases"))
  ) %>%
  ggplot(aes(x = date, y = n, color=metric)) +
  geom_line(size=1.1) +
  theme_minimal(base_size = 14) +
  theme(legend.position="top") +
  ggtitle("COVID19 USA Overall", data_last_refreshed ) +
  xlab("Days since first confirmed case") +
  ylab("Cumulative cases") +
  labs(caption = "SOURCE: New York Times Coronavirus Dataset.")

 p = p + scale_y_continuous(labels=comma_format(), trans = 'log10')

 p = p + scale_color_discrete(name="Metric",
                         breaks=c("cum_deaths", "cum_cases"),
                         labels=c("Deaths", "New Cases"))
 
 suppressWarnings(print(p))
 

```


## Confirmed Cases 


```{r, fig.width=8, fig.height=6, echo = FALSE, warning=FALSE}
# Cumulative Cases since first identified case

# Top n
us_topn_death <- usa %>%
  group_by(state) %>%
  summarise(
    max_n_cases = max(cum_deaths)
  ) %>%
  arrange(desc(max_n_cases)) %>%
  top_n(10, max_n_cases)


p <- usa %>%
  filter(cum_cases >0, state %in% us_topn_death$state) %>%
  group_by(state) %>%
  mutate(
   day = row_number()
  ) %>%
  ggplot(aes(x = day, y = cum_cases, color=state)) +
  geom_line(size=1.1) +
   geom_text_repel(size=5, aes(label=state),
                  function(us_topn_death) us_topn_death[ymd(us_topn_death$date) == data_last_refreshed, ])+
  theme_minimal(base_size = 14) +
  theme(legend.position="top") +
  ggtitle("COVID19 USA New Cases by State", data_last_refreshed ) +
  xlab("Days since first confirmed case") +
  ylab("Cumulative cases") +
  labs(caption = "SOURCE: New York Times Coronavirus Dataset.")

 p = p + scale_y_continuous(labels=comma_format(), trans = 'log10')

 p = p + scale_color_discrete(name="Metric",
                         breaks=c("cum_deaths", "cum_cases"),
                         labels=c("Deaths", "New Cases"))
 
 suppressWarnings(print(p))


```


```{r, cases-by-usa-states, fig.width=8, fig.height=6, echo = FALSE, warning=FALSE}

# Top n
us_topn_death <- usa %>%
  group_by(state) %>%
  summarise(
    max_n_cases = max(cum_deaths)
  ) %>%
  arrange(desc(max_n_cases)) %>%
  top_n(20, max_n_cases)


usa %>%
  filter(cum_cases >0, state %in% us_topn_death$state) %>%
  group_by(state) %>%
  summarise(
   n = max(cum_cases)
  ) %>%
  ggplot(aes(x = reorder(state, n), y = n), fill=state) +
  geom_bar(stat = 'identity') +
  theme(axis.text.x=element_text(angle=90,hjust=1)) +
  scale_y_continuous(labels = comma_format())+
  ggtitle("COVID19 USA cases by state", data_last_refreshed ) +
  xlab("States") +
  ylab("Cumulative cases") +
  labs(caption = "SOURCE: New York Times Coronavirus Dataset.")

```

```{r, echo=FALSE}

# USA cases by state
usa %>%
  group_by(state) %>%
  summarise(
    max_n_cases = max(cum_cases)
  ) %>%
  arrange(desc(max_n_cases)) %>%
  top_n(15, max_n_cases)%>%
  transmute(
    State = state
    , `Total cases` = max_n_cases
  ) %>%
  kable(caption = paste("Totaly cases for top 10 US States as of ", data_last_refreshed))
```



## Deaths

```{r, fig.width=8, fig.height=6, echo = FALSE, warning=FALSE}
# Cumulative Cases since first identified case

# Top n
us_topn_death <- usa %>%
  group_by(state) %>%
  summarise(
    max_n_cases = max(cum_deaths)
  ) %>%
  arrange(desc(max_n_cases)) %>%
  top_n(10, max_n_cases)


dfw <- usa %>%
  filter(cum_deaths >0, state %in% us_topn_death$state) %>%
  group_by(state) %>%
  mutate(
   day = row_number()
  )

p <- ggplot(dfw, aes(x = day, y = cum_deaths, color=state)) +
  geom_line(size=1.1) +
  geom_text_repel(size=5, aes(label=cum_deaths),
                  function(dfw) dfw[ymd(dfw$date) == data_last_refreshed, ])+
  theme_minimal(base_size = 14) +
  theme(legend.position="top") +
  ggtitle("COVID19 USA Deaths by State", data_last_refreshed ) +
  xlab("Days since first death") +
  ylab("Cumulative cases") +
  labs(caption = "SOURCE: New York Times Coronavirus Dataset.")

 p <- p + scale_y_continuous(labels=comma_format(), trans ='log10')

 # p = p + scale_color_discrete(name="Metric",
 #                         breaks=c("cum_deaths", "cum_cases"),
 #                         labels=c("Deaths", "New Cases"))
 
 suppressWarnings(print(p))

```


```{r, deaths-by-usa-states, fig.width=8, fig.height=6, echo = FALSE, warning=FALSE}
# Deaths histogram by state

# Top n
us_topn_death <- usa %>%
  group_by(state) %>%
  summarise(
    max_n_cases = max(cum_deaths)
  ) %>%
  arrange(desc(max_n_cases)) %>%
  top_n(20, max_n_cases)


usa %>%
  filter(cum_cases >0, state %in% us_topn_death$state) %>%
  group_by(state) %>%
  summarise(
   n = max(cum_deaths)
  ) %>%
  ggplot(aes(x = reorder(state, n), y = n), fill=state) +
  geom_bar(stat = 'identity') +
  theme(axis.text.x=element_text(angle=90,hjust=1)) +
  scale_y_continuous(labels = comma_format()) +
  ggtitle("COVID19 USA Deaths by State", data_last_refreshed ) +
  xlab("States") +
  ylab("Cumulative cases") +
  labs(caption = "SOURCE: New York Times Coronavirus Dataset.")

```

```{r, echo=FALSE}
# Death table USA by state
us_topn_death %>%
  transmute(
    State = state
    , `Total cases` = max_n_cases
  ) %>%
  kable(caption = paste("Totaly deaths by State as of ", data_last_refreshed))
```

## Daily Deaths {#usa-daily-deaths}


```{r, deaths-usa-daily, fig.width=8, fig.height=6, echo = FALSE, warning=FALSE}

# Deaths daily histogram

# Top n
us_daily_deaths <- usa %>%
  group_by(date) %>%
  summarize(
    total_deaths = max(cum_deaths)
  ) %>%
  mutate(
    daily_deaths = c(0, diff(total_deaths))
  )

a0 <- us_daily_deaths %>%
  ggplot(aes(x=date, y = daily_deaths)) +
  geom_bar(stat = 'identity') + geom_smooth(se=F) +
  theme(axis.text.x=element_text(angle=90,hjust=1)) +
  scale_y_continuous(labels = comma_format()) +
  ggtitle("COVID19 USA daily deaths", data_last_refreshed ) +
  xlab("Date") +
  ylab("Daily deaths") +
  labs(caption = "SOURCE: New York Times Coronavirus Dataset.")

suppressMessages(print(a0))

```


```{r, deaths-usa-ny-daily, fig.width=8, fig.height=6, echo = FALSE, warning=FALSE}

# Deaths daily histogram for New York

# Top n
ny_daily_deaths <- usa %>%
  filter(state == 'New York') %>%
  group_by(date) %>%
  summarize(
    total_deaths = max(cum_deaths)
  ) %>%
  mutate(
    daily_deaths = c(0, diff(total_deaths))
  )

a2 <- ny_daily_deaths %>%
  ggplot(aes(x=date, y = daily_deaths)) +
  geom_bar(stat = 'identity') +
  geom_smooth(se=F) +
  theme(axis.text.x=element_text(angle=90,hjust=1)) +
  scale_y_continuous(labels = comma_format()) +
  ggtitle("COVID19 USA daily deaths for New York", data_last_refreshed ) +
  xlab("Date") +
  ylab("Daily deaths") +
  labs(caption = "SOURCE: New York Times Coronavirus Dataset.")

suppressMessages(print(a2))

```


## Daily Deaths excluding NY {#usa-daily-deaths-excl-ny}


```{r, deaths-usa-daily-excl-ny, fig.width=8, fig.height=6, echo = FALSE, warning=FALSE}

# Deaths daily histogram

# Top n
us_daily_deaths_excl_ny <- usa %>%
  filter(state != 'New York') %>%
  group_by(date) %>%
  summarize(
    total_deaths = max(cum_deaths)
  ) %>%
  mutate(
    daily_deaths = c(0, diff(total_deaths))
  )

a1 <- us_daily_deaths_excl_ny %>%
  ggplot(aes(x=date, y = daily_deaths)) +
  geom_bar(stat = 'identity') +
  # geom_smooth(aes(x=date,y=daily_deaths), se=F, method="loess", show_guide = FALSE,lwd=0.7) +
  geom_smooth(se=F) +
  theme(axis.text.x=element_text(angle=90,hjust=1)) +
  scale_y_continuous(labels = comma_format()) +
  ggtitle("COVID19 USA daily deaths excluding NY", data_last_refreshed ) +
  xlab("Date") +
  ylab("Daily deaths") +
  labs(caption = "SOURCE: New York Times Coronavirus Dataset.")

suppressMessages(print(a1))
```

