
# Publications {#scipubs}

This section lists major publications with a brief summary. The latest publications are listed first. 

- Estimates of the severity of coronavirus disease 2019: a model-based analysis. https://doi.org/10.1016/S1473-3099(20)30243-7

  Using data on 24 deaths that occurred in mainland China and 165 recoveries outside of China, we estimated the mean duration from onset of symptoms to death to be 17·8 days (95% credible interval [CrI] 16·9–19·2) and to hospital discharge to be 24·7 days (22·9–28·1). In all laboratory confirmed and clinically diagnosed cases from mainland China (n=70 117), we estimated a crude case fatality ratio (adjusted for censoring) of 3·67% (95% CrI 3·56–3·80). However, after further adjusting for demography and under-ascertainment, we obtained a best estimate of the case fatality ratio in China of 1·38% (1·23–1·53), with substantially higher ratios in older age groups (0·32% [0·27–0·38] in those aged <60 years vs 6·4% [5·7–7·2] in those aged ≥60 years), up to 13·4% (11·2–15·9) in those aged 80 years or older. 
 
## Other articles

- [Why COVID19 can't be compared with flu by Ruth Etzioni](https://timmermanreport.com/2020/04/why-covid-19-cant-be-directly-compared-with-the-flu/) 
