
# Trials and Treatments {#trials}


## Clinical trials


**April 7, 2020**

- [Canada begins clinical trial of experimental COVID-19 treatment using plasma from recovered individuals](https://www.theglobeandmail.com/canada/article-canada-begins-clinical-trial-of-experimental-covid-19-treatment-using/?utm_source=Nature+Briefing&utm_campaign=97ef9daa48-briefing-dy-20200407&utm_medium=email&utm_term=0_c9dfd39373-97ef9daa48-44480057) 

> All patients who are hospitalized and need oxygen will be able to sign up for the trial.

> “It’s a flip of a coin – two-thirds of patients will get the antibody-rich blood, with the other third being a control group,” Dr. Arnold said. The control group would receive standard care.

> The trial could be completed in as little as three months. Dr. Arnold said they are realistically looking at six to 10 months before they have definitive results.

> “The challenge is to get to an answer as quickly as possible so that we can start using this product if it’s truly effective, or realize it’s not and stop using it,” Dr. Arnold said.
