--- 
title: "COVID19 Life Report"
author: "Enayetur Raheem"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: raheems/r4res
description: "Live report on COVID19 pandemic with emphasis on data visualizations and interpretations."
---


```{r, echo=FALSE, message=FALSE, cache=TRUE}
source("covid19_confirmed.R")
```

# Dashboard


__Report last updated:__ `r Sys.Date()`

__Data last refreshed:__ : `r data_last_refreshed`


```{r, covid19-confirmed-cases-world, fig.width=8, fig.height=6, echo = FALSE, warning=FALSE}
# Cumulative Cases since first identified case

ggplot(case_summary, aes(x = Day, y = cum_cases, color=country)) +
  geom_line(size=1.1) +
  geom_point(data = case_summary[case_summary$country == 'Bangladesh' & ymd(case_summary$Date)==data_last_refreshed, ],
             aes(x=Day, y=cum_cases), color='red', size=5) +
  geom_text_repel(size=5, aes(label=country),
                  function(case_summary) case_summary[ymd(case_summary$Date) == data_last_refreshed, ])+
  theme_minimal(base_size = 14) +
  theme(legend.position = "none") +
  # theme_void() +
  theme(legend.position="none") +
  ggtitle("COVID19 cumulative cases since first case \n(top 5 countries excluding China)", as.Date(last_reported_date) ) +
  xlab("Days since first confirmed case") +
  ylab("Cumulative cases")

# 
# 
# plotly::ggplotly(p)

```



